# Generated by Django 6.0.3 on 2026-05-08 14:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('agent', 'Agent'), ('directeur_activite', 'Directeur Activité'), ('directeur_direction', 'Directeur de Direction'), ('responsable_departement', 'Responsable de Département')], max_length=30, null=True)),
                ('photo_profil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activite_id', models.CharField(blank=True, max_length=24, null=True)),
                ('direction_id', models.CharField(blank=True, max_length=24, null=True)),
                ('departement_id', models.CharField(blank=True, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
