# Generated by Django 5.1.7 on 2026-06-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=500)),
                ('type_contrat', models.CharField(choices=[('service', 'Services / خدمات'), ('fourniture', 'Fournitures / توريد'), ('travaux', 'Travaux / أشغال'), ('partenariat', 'Partenariat / شراكة'), ('vente', 'Vente / بيع'), ('transfert', 'Transfert / نقل')], max_length=20)),
                ('cree_par_id', models.IntegerField()),
                ('cree_par_role', models.CharField(max_length=30)),
                ('departement_id', models.CharField(max_length=24)),
                ('direction_id', models.CharField(max_length=24)),
                ('direction_centrale_id', models.CharField(blank=True, max_length=24, null=True)),
                ('societe_a_nom', models.CharField(default='SONATRACH', max_length=255, verbose_name='Dénomination sociale Partie A (Client)')),
                ('societe_b_nom', models.CharField(max_length=255, verbose_name='Dénomination sociale Partie B (Fournisseur)')),
                ('pays_partie_b', models.CharField(max_length=100)),
                ('is_international', models.BooleanField(default=False)),
                ('type_partie', models.CharField(choices=[('nationale', 'Nationale'), ('etrangere', 'Étrangère')], default='nationale', max_length=10)),
                ('societe_a_representant_nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom représentant Client')),
                ('societe_a_representant_prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom représentant Client')),
                ('societe_a_representant_fonction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction représentant Client')),
                ('societe_b_siege_social', models.CharField(blank=True, max_length=500, null=True, verbose_name='Siège social Fournisseur')),
                ('societe_b_representant_nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom représentant Fournisseur')),
                ('societe_b_representant_prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom représentant Fournisseur')),
                ('societe_b_representant_fonction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction représentant Fournisseur')),
                ('notification_adresse_ligne1', models.CharField(blank=True, max_length=500, null=True)),
                ('notification_adresse_ligne2', models.CharField(blank=True, max_length=500, null=True)),
                ('fax_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254, null=True)),
                ('nom_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom signataire Client (Art. 22)')),
                ('prenom_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom signataire Client (Art. 22)')),
                ('fonction_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction signataire Client (Art. 22)')),
                ('nom_fournisseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom signataire Fournisseur (Art. 22)')),
                ('prenom_fournisseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom signataire Fournisseur (Art. 22)')),
                ('fonction_fournisseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction signataire Fournisseur (Art. 22)')),
                ('objet', models.TextField()),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('devise', models.CharField(default='DZD', max_length=10)),
                ('conditions_paiement', models.TextField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du document PDF')),
                ('delai_livraison_mois', models.PositiveIntegerField(blank=True, help_text='Nombre de mois accordés pour la livraison, à compter de la date de début (date_debut).', null=True, verbose_name='Délai de livraison (mois)')),
                ('date_limite_livraison', models.DateField(blank=True, editable=False, help_text='Calculé automatiquement = date_debut + delai_livraison_mois', null=True, verbose_name='Date limite de livraison (calculée automatiquement)')),
                ('fichier_original', models.FileField(blank=True, null=True, upload_to='contrats/originaux/')),
                ('fichier_format', models.CharField(blank=True, max_length=10)),
                ('texte_extrait', models.TextField(blank=True)),
                ('moteur_ocr', models.CharField(blank=True, choices=[('tesseract', 'Tesseract'), ('easyocr', 'EasyOCR'), ('azure', 'Azure Document Intelligence')], max_length=20)),
                ('ocr_effectue', models.BooleanField(default=False)),
                ('ocr_date', models.DateTimeField(blank=True, null=True)),
                ('contrat_genere', models.FileField(blank=True, null=True, upload_to='contrats/generes/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadonneeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100)),
                ('valeur', models.TextField()),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadonnees', to='clm.contrat')),
            ],
            options={
                'verbose_name': 'Métadonnée contrat',
                'unique_together': {('contrat', 'cle')},
            },
        ),
        migrations.CreateModel(
            name='RisqueContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('type_risque', models.CharField(choices=[('retard', 'Retard'), ('imprecision', 'Imprécision'), ('different', 'Différend')], max_length=15)),
                ('description', models.TextField()),
                ('severite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('critique', 'Critique')], max_length=10)),
                ('article_ref', models.CharField(blank=True, max_length=50)),
                ('suggestion', models.TextField(blank=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('niveau_alerte', models.CharField(choices=[('warning', 'Avertissement'), ('alert', 'Alerte'), ('escalade', 'Escalade')], default='warning', max_length=10)),
                ('resolu', models.BooleanField(default=False)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='clm.contrat')),
            ],
            options={
                'verbose_name': 'Risque contrat',
                'ordering': ['-severite', 'code'],
                'unique_together': {('contrat', 'code')},
            },
        ),
    ]
